version: '3.7'

networks:
  mynetwork:
    driver: bridge

services:
  app:
    container_name: backend-app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_SCHEMA=todo
    build:
      context: .
      target: builder
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - mynetwork

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./init_sql.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork